[versions]
activityCompose = "1.9.3"
androidGradlePlugin = "8.7.2"
commonsCsv = "1.12.0"
composeVersion = "1.7.5"
core = "1.6.1"
coreTesting = "1.1.1"
datastorePreferences = "1.1.1"
fit = "21.141.0"
androidHilt = "1.2.0"
javaJwt = "4.4.0"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlinPlugin = "2.1.0"
kotlinxCoroutinesTest = "1.9.0"
kotlinxSerializationJson = "1.7.3"
ksp = "2.1.0-1.0.29"
lifecycle = "2.8.7"
material3 = "1.3.1"
mockk = "1.13.13"
navigationCompose = "2.8.4"
okhttp = "4.12.0"
okhttpSignpost = "1.1.0"
retrofitVersion = "2.11.0"
roomVersion = "2.6.1"
truth = "1.4.4"
hilt = "2.52"
runner = "1.6.2"
turbine = "1.2.0"
testLogger = "4.0.0"
dependency-analysis = "2.4.2"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeVersion" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeVersion" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "composeVersion" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-test-core = { module = "androidx.test:core", version.ref = "core" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidHilt" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeVersion" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeVersion" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeVersion" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref= "androidHilt" }
commons-csv = { module = "org.apache.commons:commons-csv", version.ref = "commonsCsv" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitVersion" }
android-core-testing = { module = "android.arch.core:core-testing", version.ref = "coreTesting" }
fit = { module = "com.garmin:fit", version.ref = "fit" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
java-jwt = { module = "com.auth0:java-jwt", version.ref = "javaJwt" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
okhttp-signpost = { module = "se.akerfeldt:okhttp-signpost", version.ref = "okhttpSignpost" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-tls = { module = "com.squareup.okhttp3:okhttp-tls", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinPlugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinPlugin" }
kotlin-serializable = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinPlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "testLogger"}
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }

